---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    # Define a list of users.
    users:
      - name: molecule_user1
        state: present
        groups: molecule_group1
      - name: molecule_user2
        state: present
        groups: molecule_group2
      - name: molecule_user3
        state: absent

    # Define a list of groups.
    users_groups:
      - name: molecule_group1
        state: present
      - name: molecule_group2
        state: present
        sudo_config: "ALL=(ALL) NOPASSWD: ALL"

  pre_tasks:
    - name: Update cache (Debian)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == "Debian"

  roles:
    - leberkaslabs.users
